import Head from 'next/head'
import TheHeader from '../components/Header'
import SlideNav from '../components/SlideNav'

export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <TheHeader />
        <SlideNav />
      </main>
    </div>
  )
}
